apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-capstone
  labels:
    app: capstone-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project
      version: v1
  template:
    metadata:
      labels:
        app: capstone-project
        version: v1
    spec:
      containers:
        - name: capstone-project
          image: sayyedmo/capstone-project
          ports:
            - containerPort: 8080